### ISSUE TITLE
prune_finetune.py 执行时出现

### ISSUE THREAD

**Issue by wemindful** [ZJU-lishuang/yolov5-v6#2]
optimizer: SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
DP not recommended, instead use torch.distributed.run for best DDP Multi-GPU results.
See Multi-GPU Tutorial at https://github.com/ultralytics/yolov5/issues/475 to get started.
Traceback (most recent call last):
  File "prune_finetune.py", line 678, in <module>
    main(opt)
  File "prune_finetune.py", line 575, in main
    train(opt.hyp, opt, device, callbacks)
  File "prune_finetune.py", line 237, in train
    model.module_list = model.module.module_list
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'module_list'

**Comment by ZJU-lishuang** [comment]
DP not recommended, instead use torch.distributed.run for best DDP Multi-GPU results.

**Comment by wemindful** [comment]
The single-GPU test passed, but the multi-GPU test failed, and there was no problem with precision recovery

**Comment by a01163125** [comment]
Unbelievable this question is three years old. 
I am unable to use ddp as: 
RuntimeError: use_libuv was requested but PyTorch was build without libuv support


So I simplely commented out these couple of lines of code.
